// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutMePageDocumentDataSlicesSlice =
  | ListSlice
  | ScrollIndicatorSlice
  | CustomSpacingSlice
  | SectionTitleSlice
  | TextBlockSlice;

/**
 * Content for About Me Page documents
 */
interface AboutMePageDocumentData {
  /**
   * Slice Zone field in *About Me Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutMePageDocumentDataSlicesSlice> /**
   * Meta Description field in *About Me Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about_me_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About Me Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *About Me Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about_me_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * About Me Page document from Prismic
 *
 * - **API ID**: `about_me_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutMePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AboutMePageDocumentData>,
    "about_me_page",
    Lang
  >;

type LeadCapturePageDocumentDataSlicesSlice =
  | TextBlockSlice
  | SectionTitleSlice;

/**
 * Content for Lead Capture Page documents
 */
interface LeadCapturePageDocumentData {
  /**
   * Slice Zone field in *Lead Capture Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: lead_capture_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LeadCapturePageDocumentDataSlicesSlice> /**
   * Meta Description field in *Lead Capture Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: lead_capture_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Lead Capture Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: lead_capture_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Lead Capture Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: lead_capture_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Lead Capture Page document from Prismic
 *
 * - **API ID**: `lead_capture_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LeadCapturePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LeadCapturePageDocumentData>,
    "lead_capture_page",
    Lang
  >;

type PortfolioPageDocumentDataSlicesSlice =
  | PortfolioCardsSlice
  | ContentNavigationSlice;

/**
 * Content for Portfolio Page documents
 */
interface PortfolioPageDocumentData {
  /**
   * Slice Zone field in *Portfolio Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PortfolioPageDocumentDataSlicesSlice> /**
   * Meta Description field in *Portfolio Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: portfolio_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Portfolio Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Portfolio Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: portfolio_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Portfolio Page document from Prismic
 *
 * - **API ID**: `portfolio_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PortfolioPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PortfolioPageDocumentData>,
    "portfolio_page",
    Lang
  >;

export type AllDocumentTypes =
  | AboutMePageDocument
  | LeadCapturePageDocument
  | PortfolioPageDocument;

/**
 * Primary content in *ContentNavigation → Primary*
 */
export interface ContentNavigationSliceDefaultPrimary {
  /**
   * Headline field in *ContentNavigation → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: content_navigation.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  headline: prismic.TitleField;

  /**
   * Description field in *ContentNavigation → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_navigation.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Text Alignment field in *ContentNavigation → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Left
   * - **API ID Path**: content_navigation.primary.text_alignment
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  text_alignment: prismic.SelectField<"Left" | "Center" | "Right", "filled">;
}

/**
 * Primary content in *ContentNavigation → Items*
 */
export interface ContentNavigationSliceDefaultItem {
  /**
   * Jump Link Title field in *ContentNavigation → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_navigation.items[].jump_link_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  jump_link_title: prismic.KeyTextField;

  /**
   * Jump Link ID field in *ContentNavigation → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_navigation.items[].jump_link_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  jump_link_id: prismic.KeyTextField;
}

/**
 * Default variation for ContentNavigation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentNavigationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentNavigationSliceDefaultPrimary>,
  Simplify<ContentNavigationSliceDefaultItem>
>;

/**
 * Slice variation for *ContentNavigation*
 */
type ContentNavigationSliceVariation = ContentNavigationSliceDefault;

/**
 * ContentNavigation Shared Slice
 *
 * - **API ID**: `content_navigation`
 * - **Description**: ContentNavigation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentNavigationSlice = prismic.SharedSlice<
  "content_navigation",
  ContentNavigationSliceVariation
>;

/**
 * Primary content in *CustomSpacing → Primary*
 */
export interface CustomSpacingSliceDefaultPrimary {
  /**
   * Custom Space Value (px) field in *CustomSpacing → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: custom_spacing.primary.custom_space_value
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  custom_space_value: prismic.NumberField;
}

/**
 * Default variation for CustomSpacing Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CustomSpacingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CustomSpacingSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CustomSpacing*
 */
type CustomSpacingSliceVariation = CustomSpacingSliceDefault;

/**
 * CustomSpacing Shared Slice
 *
 * - **API ID**: `custom_spacing`
 * - **Description**: CustomSpacing
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CustomSpacingSlice = prismic.SharedSlice<
  "custom_spacing",
  CustomSpacingSliceVariation
>;

/**
 * Primary content in *List → Primary*
 */
export interface ListSliceDefaultPrimary {
  /**
   * List Title field in *List → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: list.primary.list_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  list_title: prismic.RichTextField;

  /**
   * List Title Alignment field in *List → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Left
   * - **API ID Path**: list.primary.list_title_alignment
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  list_title_alignment: prismic.SelectField<
    "Left" | "Center" | "Right",
    "filled"
  >;

  /**
   * List Description field in *List → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: list.primary.list_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  list_description: prismic.RichTextField;

  /**
   * List Description Alignment field in *List → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Left
   * - **API ID Path**: list.primary.list_description_alignment
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  list_description_alignment: prismic.SelectField<
    "Left" | "Center" | "Right",
    "filled"
  >;

  /**
   * List Items field in *List → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: list.primary.list_items_1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  list_items_1: prismic.RichTextField;

  /**
   * Scroll Animation field in *List → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: list.primary.scroll_animation
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  scroll_animation: prismic.SelectField<"Fade In Bottom" | "Fade In Top">;

  /**
   * List Items Alignment field in *List → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Left
   * - **API ID Path**: list.primary.list_items_alignment
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  list_items_alignment: prismic.SelectField<
    "Left" | "Center" | "Right",
    "filled"
  >;
}

/**
 * Default variation for List Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ListSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *List → Primary*
 */
export interface ListSliceListTwoColumnPrimary {
  /**
   * List Title field in *List → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: list.primary.list_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  list_title: prismic.RichTextField;

  /**
   * List Title Alignment field in *List → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Left
   * - **API ID Path**: list.primary.list_title_alignment
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  list_title_alignment: prismic.SelectField<
    "Left" | "Center" | "Right",
    "filled"
  >;

  /**
   * List Description field in *List → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: list.primary.list_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  list_description: prismic.RichTextField;

  /**
   * List Description Alignment field in *List → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Left
   * - **API ID Path**: list.primary.list_description_alignment
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  list_description_alignment: prismic.SelectField<
    "Left" | "Center" | "Right",
    "filled"
  >;

  /**
   * List Items 1 field in *List → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: list.primary.list_items_1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  list_items_1: prismic.RichTextField;

  /**
   * List Items 2 field in *List → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: list.primary.list_items_2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  list_items_2: prismic.RichTextField;

  /**
   * Scroll Animation field in *List → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: list.primary.scroll_animation
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  scroll_animation: prismic.SelectField<"Fade In Bottom" | "Fade In Top">;

  /**
   * List Items Alignment field in *List → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Left
   * - **API ID Path**: list.primary.list_items_alignment
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  list_items_alignment: prismic.SelectField<
    "Left" | "Center" | "Right",
    "filled"
  >;
}

/**
 * List Two Column variation for List Slice
 *
 * - **API ID**: `listTwoColumn`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ListSliceListTwoColumn = prismic.SharedSliceVariation<
  "listTwoColumn",
  Simplify<ListSliceListTwoColumnPrimary>,
  never
>;

/**
 * Primary content in *List → Primary*
 */
export interface ListSliceListThreeColumnPrimary {
  /**
   * List Title field in *List → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: list.primary.list_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  list_title: prismic.RichTextField;

  /**
   * List Title Alignment field in *List → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Left
   * - **API ID Path**: list.primary.list_title_alignment
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  list_title_alignment: prismic.SelectField<
    "Left" | "Center" | "Right",
    "filled"
  >;

  /**
   * List Description field in *List → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: list.primary.list_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  list_description: prismic.RichTextField;

  /**
   * List Description Alignment field in *List → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: list.primary.list_description_alignment
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  list_description_alignment: prismic.SelectField<"Left" | "Center" | "Right">;

  /**
   * List Items 1 field in *List → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: list.primary.list_items_1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  list_items_1: prismic.RichTextField;

  /**
   * List Items 2 field in *List → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: list.primary.list_items_2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  list_items_2: prismic.RichTextField;

  /**
   * List Items 3 field in *List → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: list.primary.list_items_3
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  list_items_3: prismic.RichTextField;

  /**
   * Scroll Animation field in *List → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: list.primary.scroll_animation
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  scroll_animation: prismic.SelectField<"Fade In Bottom" | "Fade in Top">;

  /**
   * List Items Alignment field in *List → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Left
   * - **API ID Path**: list.primary.list_items_alignment
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  list_items_alignment: prismic.SelectField<
    "Left" | "Center" | "Right",
    "filled"
  >;
}

/**
 * List Three Column variation for List Slice
 *
 * - **API ID**: `listThreeColumn`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ListSliceListThreeColumn = prismic.SharedSliceVariation<
  "listThreeColumn",
  Simplify<ListSliceListThreeColumnPrimary>,
  never
>;

/**
 * Slice variation for *List*
 */
type ListSliceVariation =
  | ListSliceDefault
  | ListSliceListTwoColumn
  | ListSliceListThreeColumn;

/**
 * List Shared Slice
 *
 * - **API ID**: `list`
 * - **Description**: List
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ListSlice = prismic.SharedSlice<"list", ListSliceVariation>;

/**
 * Primary content in *PortfolioCards → Primary*
 */
export interface PortfolioCardsSliceDefaultPrimary {
  /**
   * Headline field in *PortfolioCards → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_cards.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  headline: prismic.RichTextField;

  /**
   * Description field in *PortfolioCards → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_cards.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Text Alignment field in *PortfolioCards → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Left
   * - **API ID Path**: portfolio_cards.primary.text_alignment
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  text_alignment: prismic.SelectField<"Left" | "Center" | "Right", "filled">;

  /**
   * HTML ID field in *PortfolioCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_cards.primary.html_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  html_id: prismic.KeyTextField;
}

/**
 * Primary content in *PortfolioCards → Items*
 */
export interface PortfolioCardsSliceDefaultItem {
  /**
   * Work Example Image field in *PortfolioCards → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_cards.items[].work_example_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  work_example_image: prismic.ImageField<never>;

  /**
   * Work Example Title field in *PortfolioCards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_cards.items[].work_example_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  work_example_title: prismic.KeyTextField;

  /**
   * Work Example Description field in *PortfolioCards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_cards.items[].work_example_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  work_example_description: prismic.KeyTextField;

  /**
   * Work Example Skills field in *PortfolioCards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_cards.items[].work_example_skills
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  work_example_skills: prismic.KeyTextField;

  /**
   * Work Example Link field in *PortfolioCards → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_cards.items[].work_example_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  work_example_link: prismic.LinkField;

  /**
   * Work Example Code Link field in *PortfolioCards → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio_cards.items[].work_example_code_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  work_example_code_link: prismic.LinkField;
}

/**
 * Default variation for PortfolioCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PortfolioCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PortfolioCardsSliceDefaultPrimary>,
  Simplify<PortfolioCardsSliceDefaultItem>
>;

/**
 * Slice variation for *PortfolioCards*
 */
type PortfolioCardsSliceVariation = PortfolioCardsSliceDefault;

/**
 * PortfolioCards Shared Slice
 *
 * - **API ID**: `portfolio_cards`
 * - **Description**: PortfolioCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PortfolioCardsSlice = prismic.SharedSlice<
  "portfolio_cards",
  PortfolioCardsSliceVariation
>;

/**
 * Primary content in *ScrollIndicator → Primary*
 */
export interface ScrollIndicatorSliceDefaultPrimary {
  /**
   * Image field in *ScrollIndicator → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: scroll_indicator.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Text field in *ScrollIndicator → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: scroll_indicator.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Image Text Flow field in *ScrollIndicator → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Top Bottom
   * - **API ID Path**: scroll_indicator.primary.image_text_flow
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  image_text_flow: prismic.SelectField<
    "Top Bottom" | "Bottom Top" | "Left Right" | "Right Left",
    "filled"
  >;

  /**
   * Scroll Indicator Type field in *ScrollIndicator → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Chevron
   * - **API ID Path**: scroll_indicator.primary.scroll_indicator_type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  scroll_indicator_type: prismic.SelectField<"Chevron" | "Arrow", "filled">;

  /**
   * Scroll Indicator Animation field in *ScrollIndicator → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Static
   * - **API ID Path**: scroll_indicator.primary.scroll_indicator_animation
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  scroll_indicator_animation: prismic.SelectField<
    "Static" | "Bounce",
    "filled"
  >;
}

/**
 * Default variation for ScrollIndicator Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ScrollIndicatorSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ScrollIndicatorSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ScrollIndicator*
 */
type ScrollIndicatorSliceVariation = ScrollIndicatorSliceDefault;

/**
 * ScrollIndicator Shared Slice
 *
 * - **API ID**: `scroll_indicator`
 * - **Description**: ScrollIndicator
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ScrollIndicatorSlice = prismic.SharedSlice<
  "scroll_indicator",
  ScrollIndicatorSliceVariation
>;

/**
 * Primary content in *SectionTitle → Primary*
 */
export interface SectionTitleSliceDefaultPrimary {
  /**
   * Section Title Text field in *SectionTitle → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_title.primary.section_title_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_title_text: prismic.RichTextField;

  /**
   * Section Title Alignment field in *SectionTitle → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Left
   * - **API ID Path**: section_title.primary.section_title_alignment
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  section_title_alignment: prismic.SelectField<
    "Left" | "Center" | "Right",
    "filled"
  >;

  /**
   * Scroll Animation field in *SectionTitle → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: section_title.primary.scroll_animation
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  scroll_animation: prismic.SelectField<
    "None" | "Fade In Bottom" | "Fade In Top",
    "filled"
  >;
}

/**
 * Default variation for SectionTitle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionTitleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SectionTitleSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SectionTitle*
 */
type SectionTitleSliceVariation = SectionTitleSliceDefault;

/**
 * SectionTitle Shared Slice
 *
 * - **API ID**: `section_title`
 * - **Description**: SectionTitle
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionTitleSlice = prismic.SharedSlice<
  "section_title",
  SectionTitleSliceVariation
>;

/**
 * Primary content in *TextBlock → Primary*
 */
export interface TextBlockSliceDefaultPrimary {
  /**
   * Text Block Copy field in *TextBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.text_block_copy
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_block_copy: prismic.RichTextField;

  /**
   * Alignment field in *TextBlock → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: left
   * - **API ID Path**: text_block.primary.text_block_alignment
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  text_block_alignment: prismic.SelectField<
    "left" | "center" | "right",
    "filled"
  >;

  /**
   * Scroll Animation field in *TextBlock → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: text_block.primary.scroll_animation
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  scroll_animation: prismic.SelectField<
    "None" | "Fade In Bottom" | "Fade In Top",
    "filled"
  >;

  /**
   * Set Full Bleed field in *TextBlock → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: text_block.primary.set_full_bleed
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  set_full_bleed: prismic.BooleanField;

  /**
   * Custom Class (Use Lower Kebab Case) field in *TextBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: custom-text-block
   * - **API ID Path**: text_block.primary.custom_class
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  custom_class: prismic.KeyTextField;
}

/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextBlock*
 */
type TextBlockSliceVariation = TextBlockSliceDefault;

/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: TextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSlice = prismic.SharedSlice<
  "text_block",
  TextBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutMePageDocument,
      AboutMePageDocumentData,
      AboutMePageDocumentDataSlicesSlice,
      LeadCapturePageDocument,
      LeadCapturePageDocumentData,
      LeadCapturePageDocumentDataSlicesSlice,
      PortfolioPageDocument,
      PortfolioPageDocumentData,
      PortfolioPageDocumentDataSlicesSlice,
      AllDocumentTypes,
      ContentNavigationSlice,
      ContentNavigationSliceDefaultPrimary,
      ContentNavigationSliceDefaultItem,
      ContentNavigationSliceVariation,
      ContentNavigationSliceDefault,
      CustomSpacingSlice,
      CustomSpacingSliceDefaultPrimary,
      CustomSpacingSliceVariation,
      CustomSpacingSliceDefault,
      ListSlice,
      ListSliceDefaultPrimary,
      ListSliceListTwoColumnPrimary,
      ListSliceListThreeColumnPrimary,
      ListSliceVariation,
      ListSliceDefault,
      ListSliceListTwoColumn,
      ListSliceListThreeColumn,
      PortfolioCardsSlice,
      PortfolioCardsSliceDefaultPrimary,
      PortfolioCardsSliceDefaultItem,
      PortfolioCardsSliceVariation,
      PortfolioCardsSliceDefault,
      ScrollIndicatorSlice,
      ScrollIndicatorSliceDefaultPrimary,
      ScrollIndicatorSliceVariation,
      ScrollIndicatorSliceDefault,
      SectionTitleSlice,
      SectionTitleSliceDefaultPrimary,
      SectionTitleSliceVariation,
      SectionTitleSliceDefault,
      TextBlockSlice,
      TextBlockSliceDefaultPrimary,
      TextBlockSliceVariation,
      TextBlockSliceDefault,
    };
  }
}
